# -*- coding: utf-8 -*-
"""server.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XL4rH0n77_hrI3OubZWy4ptpSZkSbTbF
"""

from fastai.vision.learner import load_learner

export_file_url = ''
export_file_name = 'squeezenet_model'

classes=['ring', 'bracelet', 'necklace', 'earrings']

path = Path(__file__).parent



